export const SET_USER = 'USER:SET_USER'
export const CLEAR_USER = 'USER:CLEAR_USER'
export const SET_CURRENT_CHANNEL = 'CHANNEL:SET_CURRENT_CHANNEL'
export const GET_CHANNEL_MESSAGES = 'CHANNEL:LOAD_CHANNEL_MESSAGES'
